/*
 * Copyright (c) 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2020 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "lwip/opt.h"


//############################################################################################################################################//
//##-------------------Most of this file was generated by MCU default configurations when i created it as ethernet project------------------##//
//############################################################################################################################################//



#if LWIP_NETCONN

#include "tcpecho.h"
#include "lwip/netifapi.h"
#include "lwip/tcpip.h"
#include "netif/ethernet.h"
#include "enet_ethernetif.h"

#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_phy.h"

#include "fsl_phyksz8081.h"
#include "fsl_enet_mdio.h"
#include "fsl_device_registers.h"
#include"net_client.h"
#include "flash_logger.h"


//#include "peripherals.h"
#include "pin_mux.h"
#include "clock_config.h"

#include "fsl_i2c.h"
#include "fsl_clock.h"
#include "fsl_port.h"
#include "fsl_gpio.h"

#include "queue.h"

#include "rtc.h"
#include "servo.h"
#include "display.h"
#include "weight_task.h"
#include "reminder.h"
#include "alert.h"
#include "logging.h"
#include "weight.h"
#include "dispense_verify.h"
#include "server_logger.h"
#include "ai_parser.h"
#include "remote_command.h"
#include "twin_task.c"
#include <stdio.h>
#include <string.h>


/*******************************************************************************
 * Definitions
 ******************************************************************************/

/* @TEST_ANCHOR */

/* IP address configuration. */
#ifndef configIP_ADDR0
#define configIP_ADDR0 192
#endif
#ifndef configIP_ADDR1
#define configIP_ADDR1 168
#endif
#ifndef configIP_ADDR2
#define configIP_ADDR2 56
#endif
#ifndef configIP_ADDR3
#define configIP_ADDR3 20
#endif

/* Netmask configuration. */
#ifndef configNET_MASK0
#define configNET_MASK0 255
#endif
#ifndef configNET_MASK1
#define configNET_MASK1 255
#endif
#ifndef configNET_MASK2
#define configNET_MASK2 255
#endif
#ifndef configNET_MASK3
#define configNET_MASK3 0
#endif

/* Gateway address configuration. */
#ifndef configGW_ADDR0
#define configGW_ADDR0 192
#endif
#ifndef configGW_ADDR1
#define configGW_ADDR1 168
#endif
#ifndef configGW_ADDR2
#define configGW_ADDR2 56
#endif
#ifndef configGW_ADDR3
#define configGW_ADDR3 1
#endif

/* MAC address configuration. */
#ifndef configMAC_ADDR
#define configMAC_ADDR                     \
    {                                      \
        0x02, 0x12, 0x13, 0x10, 0x15, 0x11 \
    }
#endif

/* Address of PHY interface. */
#define EXAMPLE_PHY_ADDRESS BOARD_ENET0_PHY_ADDRESS

/* MDIO operations. */
#define EXAMPLE_MDIO_OPS enet_ops

/* PHY operations. */
#define EXAMPLE_PHY_OPS phyksz8081_ops

/* ENET clock frequency. */
#define EXAMPLE_CLOCK_FREQ CLOCK_GetFreq(kCLOCK_CoreSysClk)

#ifndef EXAMPLE_NETIF_INIT_FN
/*! @brief Network interface initialization function. */
#define EXAMPLE_NETIF_INIT_FN ethernetif0_init
#endif /* EXAMPLE_NETIF_INIT_FN */

/*! @brief Stack size of the temporary lwIP initialization thread. */
#define INIT_THREAD_STACKSIZE 1024

/*! @brief Priority of the temporary lwIP initialization thread. */
#define INIT_THREAD_PRIO DEFAULT_THREAD_PRIO

/*******************************************************************************
 * Prototypes
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
static QueueHandle_t g_timeQ;

static DoseTime g_schedule[] = {
    {
        .hour = 18,
        .minute = 6,
        .med_id = "MedA",
        .ai_high_risk = false,
        .prealert_lead_sec = 0,
        .prealert_sent_today = false,
        .reminder_sent_today = false
    },

    {
        .hour = 13,
        .minute = 33,
        .med_id = "MedE",
        .ai_high_risk = false,
        .prealert_lead_sec = 0,
        .prealert_sent_today = false,
        .reminder_sent_today = false
    },

//    {
//        .hour = 12,
//        .minute = 15,
//        .med_id = "MedC",
//        .ai_high_risk = false,
//        .prealert_lead_sec = 0,
//        .prealert_sent_today = false,
//        .reminder_sent_today = false
//    },
//    {
//        .hour = 12,
//        .minute = 18,
//        .med_id = "MedD",
//        .ai_high_risk = false,
//        .prealert_lead_sec = 0,
//        .prealert_sent_today = false,
//        .reminder_sent_today = false
//    },
};

static DoseTime g_nextDose;

typedef struct
{
    uint32_t timestamp_ms;
    bool     reminder_active;
    bool     ai_high_risk;
    int16_t  servo_state_deg;
    int16_t  weight_grams;
} TwinState_t;

static TwinState_t g_twin_state;





static mdio_handle_t mdioHandle = {.ops = &EXAMPLE_MDIO_OPS};
static phy_handle_t phyHandle   = {.phyAddr = EXAMPLE_PHY_ADDRESS, .mdioHandle = &mdioHandle, .ops = &EXAMPLE_PHY_OPS};

/*******************************************************************************
 * Code
 ******************************************************************************/


// =====================
// I2C1 init helper
// =====================


static void I2C1_BusInit(void)
{
    CLOCK_EnableClock(kCLOCK_PortC);
    CLOCK_EnableClock(kCLOCK_I2c1);

    port_pin_config_t i2c_config = {
        .pullSelect = kPORT_PullDisable,
        .slewRate = kPORT_FastSlewRate,
        .passiveFilterEnable = kPORT_PassiveFilterDisable,
        .openDrainEnable = kPORT_OpenDrainEnable,
        .driveStrength = kPORT_LowDriveStrength,
        .mux = kPORT_MuxAlt2,
        .lockRegister = kPORT_UnlockRegister
    };

    PORT_SetPinConfig(PORTC, 10U, &i2c_config);   // PTC10 = I2C1_SCL
    PORT_SetPinConfig(PORTC, 11U, &i2c_config);   // PTC11 = I2C1_SDA

    i2c_master_config_t masterConfig;
    I2C_MasterGetDefaultConfig(&masterConfig);
    masterConfig.baudRate_Bps = 100000U;

    I2C_MasterInit(I2C1, &masterConfig, CLOCK_GetFreq(I2C1_CLK_SRC));
}

// =====================
// Helpers
// =====================


//###############################################################################//
//##-------------------AI Generated from line 257 to line 360------------------##//
//###############################################################################//


static void compute_next_dose(const RtcTime *now, DoseTime *out)
{
    DoseTime best = g_schedule[0];
    bool found = false;

    for (uint32_t i = 0; i < (sizeof(g_schedule) / sizeof(g_schedule[0])); i++)
    {
        const uint8_t h = g_schedule[i].hour;
        const uint8_t m = g_schedule[i].minute;

        if ((now->hour < h) || ((now->hour == h) && (now->minute < m)))
        {
            best.hour = h;
            best.minute = m;
            found = true;
            break;
        }
    }

    if (!found)
    {
        best = g_schedule[0];
    }

    *out = best;
}

static bool AI_IsHighRiskCurrent(void)
{
    return false;
}


static void Task_RTC(void *pv)
{
    (void)pv;
    RtcTime t;

    while (1)
    {
        if (RTC_GetTime(&t))
        {
            (void)xQueueOverwrite(g_timeQ, &t);
            Reminder_OnSecondTick(&t);
        }

        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

static void Task_Display(void *pv)
{
    (void)pv;
    RtcTime t;

    while (1)
    {
        if (xQueueReceive(g_timeQ, &t, pdMS_TO_TICKS(100)) == pdTRUE)
        {
            compute_next_dose(&t, &g_nextDose);

            if (!Reminder_IsActive() && !Display_IsHoldActive())
            {
                Display_ShowTime(&t, &g_nextDose);
            }

        }

        vTaskDelay(pdMS_TO_TICKS(250));
    }
}


static void Task_CommandPoll(void *pv)
{
    (void)pv;

    char cmd[32];

    while (1)
    {
        memset(cmd, 0, sizeof(cmd));

        if (NetClient_GetCommand("/api/command", cmd, sizeof(cmd)))
        {
            if (cmd[0] != '\0')
            {
                PRINTF("SYS,REMOTE_CMD_FETCH,%s\r\n", cmd);

                if (strcmp(cmd, "NONE") != 0)
                {
                    (void)RemoteCommand_Handle(cmd);
                }
            }
        }
        else
        {
            PRINTF("SYS,REMOTE_CMD_FETCH_FAIL\r\n");
        }

        vTaskDelay(pdMS_TO_TICKS(1500));
    }
}

// Optional stack overflow hook
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    taskDISABLE_INTERRUPTS();
    for (;;)
    {
    }
}

static void Task_Button(void *pv)
{
    (void)pv;

    bool prev_sw2 = false;
    bool prev_sw3 = false;

    while (1)
    {
        bool sw2_pressed = (GPIO_PinRead(GPIOD, 11U) == 0U); // SW2 LOG VIEW
        bool sw3_pressed = (GPIO_PinRead(GPIOA, 10U) == 0U); // SW3 SNOOZE

        if (sw2_pressed && !prev_sw2)
        {
            PRINTF("SW2 press detected (LOG VIEW)\r\n");
            Display_ShowNextStoredLog();
        }

        if (sw3_pressed && !prev_sw3)
        {
            PRINTF("SW3 press detected (SNOOZE)\r\n");
            Reminder_SnoozeFromISR();
        }

        prev_sw2 = sw2_pressed;
        prev_sw3 = sw3_pressed;

        vTaskDelay(pdMS_TO_TICKS(50));
    }
}



/*!
 * @brief Initializes lwIP stack.
 *
 * @param arg unused
 */

static void stack_init(void *arg)
{
    static struct netif netif;
    ip4_addr_t netif_ipaddr, netif_netmask, netif_gw;
    ethernetif_config_t enet_config = {
        .phyHandle  = &phyHandle,
        .macAddress = configMAC_ADDR,
    };

    LWIP_UNUSED_ARG(arg);

    mdioHandle.resource.csrClock_Hz = EXAMPLE_CLOCK_FREQ;

    IP4_ADDR(&netif_ipaddr, configIP_ADDR0, configIP_ADDR1, configIP_ADDR2, configIP_ADDR3);
    IP4_ADDR(&netif_netmask, configNET_MASK0, configNET_MASK1, configNET_MASK2, configNET_MASK3);
    IP4_ADDR(&netif_gw, configGW_ADDR0, configGW_ADDR1, configGW_ADDR2, configGW_ADDR3);

    tcpip_init(NULL, NULL);

    netifapi_netif_add(&netif, &netif_ipaddr, &netif_netmask, &netif_gw, &enet_config, EXAMPLE_NETIF_INIT_FN,
                       tcpip_input);
    netifapi_netif_set_default(&netif);
    netifapi_netif_set_up(&netif);

    PRINTF("\r\n************************************************\r\n");
    PRINTF(" TCP Echo example\r\n");
    PRINTF("************************************************\r\n");
    PRINTF(" IPv4 Address     : %u.%u.%u.%u\r\n", ((u8_t *)&netif_ipaddr)[0], ((u8_t *)&netif_ipaddr)[1],
           ((u8_t *)&netif_ipaddr)[2], ((u8_t *)&netif_ipaddr)[3]);
    PRINTF(" IPv4 Subnet mask : %u.%u.%u.%u\r\n", ((u8_t *)&netif_netmask)[0], ((u8_t *)&netif_netmask)[1],
           ((u8_t *)&netif_netmask)[2], ((u8_t *)&netif_netmask)[3]);
    PRINTF(" IPv4 Gateway     : %u.%u.%u.%u\r\n", ((u8_t *)&netif_gw)[0], ((u8_t *)&netif_gw)[1],
           ((u8_t *)&netif_gw)[2], ((u8_t *)&netif_gw)[3]);
    PRINTF("************************************************\r\n");
   SDK_DelayAtLeastUs(800000, CLOCK_GetCoreSysClkFreq());


    if (!NetClient_Init("192.168.56.10", 5000))
    {
        PRINTF("[NET CLIENT] Init failed\r\n");
    }

    I2C1_BusInit();
    PRINTF("I2C1 initialized\r\n");


    if (!RTC_AppInit())
    {
        PRINTF("RTC_AppInit failed\r\n");
    }
    else
    {
         PRINTF("RTC_AppInit OK\r\n");

//         RtcTime setTime = {
//             .year = 2026,
//             .month = 3,
//             .day = 24,
//             .hour = 15,
//             .minute = 53,
//             .second = 0,
//             .dow = 3
//         };
//         RTC_SetTime(&setTime);
//         PRINTF("RTC manually set\r\n");
    }

    if (!Display_Init())
    {
        PRINTF("Display_Init failed\r\n");
    }
    else
    {
        PRINTF("Display_Init OK\r\n");
        Display_ShowBoot();
    }

    /* Load reminder schedule BEFORE AI sync so med IDs exist */
    Reminder_Init();
    Reminder_SetSchedule(g_schedule,
                         (uint8_t)(sizeof(g_schedule) / sizeof(g_schedule[0])));
    PRINTF("Reminder init OK\r\n");


    AI_BootSync();

    DispenseVerify_Init();
    PRINTF("DispenseVerify init OK\r\n");

    if (!ServerLogger_Init())
    {
        PRINTF("ServerLogger init failed\r\n");
    }
    else
    {
        PRINTF("ServerLogger init OK\r\n");
    }

    /* Start noisier/background modules AFTER AI sync */
    Logging_Init();
    if (!Logging_TaskInit())
    {
        PRINTF("Logging_TaskInit failed\r\n");
    }
    else
    {
        PRINTF("Logging_TaskInit OK\r\n");
    }

    PRINTF("DBG,BEFORE_FLASH_INIT\r\n");
    if (!FlashLogger_Init())
    {
        PRINTF("FlashLogger init failed\r\n");
    }
    else
    {
        PRINTF("FlashLogger init OK\r\n");
//        FlashLogger_EraseAll();
        Reminder_LoadAllRiskWeights();

    }


    PRINTF("DBG,AFTER_FLASH_INIT\r\n");

    PRINTF("DBG,BEFORE_RISK_REBUILD\r\n");
    Reminder_RebuildRiskFromFlash();
    PRINTF("DBG,AFTER_RISK_REBUILD\r\n");


    if (!Alert_Init())
    {
        PRINTF("Alert_Init failed\r\n");
    }
    else
    {
        PRINTF("Alert_Init OK\r\n");
    }

    if (!Servo_Init())
    {
        PRINTF("Servo_Init failed\r\n");
    }
    else
    {
        PRINTF("Servo_Init OK\r\n");
    }

    if (!Weight_Task_Init())
    {
        PRINTF("Weight task create failed\r\n");
    }
    else
    {
        PRINTF("Weight task create OK\r\n");
    }

    SDK_DelayAtLeastUs(800000, CLOCK_GetCoreSysClkFreq());



    g_timeQ = xQueueCreate(1, sizeof(RtcTime));
    if (g_timeQ == NULL)
    {
        PRINTF("Queue create failed\r\n");
        vTaskDelete(NULL);
        return;
    }

    if (xTaskCreate(Task_RTC, "RTC", 512, NULL, tskIDLE_PRIORITY + 3, NULL) != pdPASS)
    {
        PRINTF("Task_RTC create failed\r\n");
        vTaskDelete(NULL);
        return;
    }

    if (xTaskCreate(Task_Display, "DISP", 512, NULL, tskIDLE_PRIORITY + 2, NULL) != pdPASS)
    {
        PRINTF("Task_Display create failed\r\n");
    }
    else
    {
        PRINTF("Task_Display create OK\r\n");
    }

    if (xTaskCreate(Task_Button, "BTN", 256, NULL, tskIDLE_PRIORITY + 2, NULL) != pdPASS)
    {
        PRINTF("Task_Button create failed\r\n");
    }
    else
    {
        PRINTF("Task_Button create OK\r\n");
    }


    if (xTaskCreate(Task_TwinBroadcast, "TWIN", 256, NULL, tskIDLE_PRIORITY + 1, NULL) != pdPASS)
    {
        PRINTF("Task_TwinBroadcast create failed\r\n");
    }
    else
    {
        PRINTF("Task_TwinBroadcast create OK\r\n");
    }

    if (xTaskCreate(Task_CommandPoll, "CMD", 512, NULL, tskIDLE_PRIORITY + 1, NULL) != pdPASS)
    {
        PRINTF("Task_CommandPoll create failed\r\n");
    }
    else
    {
        PRINTF("Task_CommandPoll create OK\r\n");
    }

    PRINTF("Medication tasks started\r\n");

    vTaskDelete(NULL);


}



/*!
 * @brief Main function
 */
int main(void)
{
    SYSMPU_Type *base = SYSMPU;
    BOARD_InitBootPins();
    BOARD_InitBootClocks();
//    BOARD_InitBootPeripherals();
//    BOARD_InitBUTTONsPins();

    CLOCK_EnableClock(kCLOCK_PortD);

    port_pin_config_t sw2_cfg = {
        .pullSelect = kPORT_PullUp,
        .slewRate = kPORT_FastSlewRate,
        .passiveFilterEnable = kPORT_PassiveFilterDisable,
        .openDrainEnable = kPORT_OpenDrainDisable,
        .driveStrength = kPORT_LowDriveStrength,
        .mux = kPORT_MuxAsGpio,
        .lockRegister = kPORT_UnlockRegister
    };

    PORT_SetPinConfig(PORTD, 11U, &sw2_cfg);

    gpio_pin_config_t sw2_gpio = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };

    GPIO_PinInit(GPIOD, 11U, &sw2_gpio);

    CLOCK_EnableClock(kCLOCK_PortA);

    port_pin_config_t sw3_cfg = {
        .pullSelect = kPORT_PullUp,
        .slewRate = kPORT_FastSlewRate,
        .passiveFilterEnable = kPORT_PassiveFilterDisable,
        .openDrainEnable = kPORT_OpenDrainDisable,
        .driveStrength = kPORT_LowDriveStrength,
        .mux = kPORT_MuxAsGpio,
        .lockRegister = kPORT_UnlockRegister
    };

    PORT_SetPinConfig(PORTA, 10U, &sw3_cfg);

    gpio_pin_config_t sw3_gpio = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };

    GPIO_PinInit(GPIOA, 10U, &sw3_gpio);


    BOARD_InitDebugConsole();
    /* Disable SYSMPU. */
    base->CESR &= ~SYSMPU_CESR_VLD_MASK;
    /* Set RMII clock src. */
    SIM->SOPT2 |= SIM_SOPT2_RMIISRC_MASK;

    /* Initialize lwIP from thread */
    if (sys_thread_new("main", stack_init, NULL, INIT_THREAD_STACKSIZE, INIT_THREAD_PRIO) == NULL)
    {
        LWIP_ASSERT("main(): Task creation failed.", 0);
    }

    vTaskStartScheduler();

    /* Will not get here unless a task calls vTaskEndScheduler ()*/
    return 0;
}
#endif
